### ISSUE TITLE
과제 제출 양식은 코드 파일만 올리면 되는 걸까요?

### ISSUE THREAD

**Issue by wonjinzz** [PLASS-Lab/CDT#1]
과제 제출 양식은 코드 파일만 올리면 되는 걸까요?

**Comment by PLASS-Lab** [comment]
과제 제출은 다음 내용을 포함하시면 아주 좋습니다.

1. 보고서
 - 과제/문제 분석 내용 설명
 - 주요 알고리즘/코드 설명
 - 실행 결과 및 분석
 - 소감 및 추가 제언, 고민 내용 등

2. 프로그램 코드 압축파일
 - 추가 구현/수정된 부분의 주석 포함
