### ISSUE TITLE
추가 과제(마방진)에 대해 질문이 있습니다!!

### ISSUE THREAD

**Issue by Dice15** [PLASS-Lab/CDT#2]
질문 1) 추가 과제는 U-Code 파일만 제출하는 건가요? 아니면 보고서에 마방진 코드에 대한 분석도 작성해야 하나요?

질문 2) 입력 조건에 대한 질문 (입력으로 3~15 범위를 벗어난 '홀수'가 주어지는 경우에는 어떻게 해야 하나요?)

i) 별다른 처리를 하지 않는다
ii) 입력을 다시 입력 받는다
iii) 프로그램을 종료한다

**Comment by PLASS-Lab** [comment]
질문에 대합 답변입니다.

1) 추가과제는 마방진 U-Code 파일과 함께 보고서에 해당 내용에 대한 설명이 작성되어야 합니다.
2) 입력 조건을 벗어난 경우(짝수 또는 홀수의 범위를 벗어난 경우)는 다시 입력 받도록 처리해주시기 바랍니다.
