### ISSUE TITLE
ch07 31페이지 질문

### ISSUE THREAD

**Issue by yoons02** [PLASS-Lab/CDT#3]
안녕하세요. 질문이 있어 issue 올립니다.
교안 ch07 31페이지에서 parsing table을 만들 때 first, follow를 먼저 계산하고
lookahead를 계산 한 후에 교집합이 없으면 LL(1)을 만족한다라고 이해했습니다.

S -> aSb
S -> bA
A -> Aa
A -> b
예제를 보면 문법 G가 위와 같이 정의되어 있을 때, 제가 계산한 first, follow는 다음과 같습니다.

FIRST(S) = {a,b}
FIRST(A) = {b}
FOLLOW(S) = {$, b} U FOLLOW(A)
FOLLOW(A) = {a} U FOLLOW(S)

Lookahead 계산은 다음과 같습니다.

LOOKAHEAD(S->aSb) = {a} ...(1)
LOOKAHEAD(S->bA) = {b} ...(2)
LOOKAHEAD(A -> Aa) = {b} ...(3)
LOOKAHEAD(A -> b) = {b} ...(4)

(1)과 (2)의 교집합은 공집합
(3)과 (4)의 교칩합은 {b}이므로 LL(1)을 만족하지 않는다고 풀리는데 이 과정에서 저의 질문은 다음과 같습니다.

1. FOLLOW를 계산할 때 위처럼 서로가 포함하고 있으면 어떻게 풀어야 하는지
2. 위 예제는 LL(1)을 만족하지 않는게 맞는지

답변해주시면 감사하겠습니다.

**Comment by PLASS-Lab** [comment]
먼저 예제에 대한 설명입니다.

1. FOLLOW(S) = {$, b} 이며, FOLLOW(A)의 합집합이 필요하지 않습니다.
2. 3번 생성규칙은 오타입니다. left recursion이 존재하면, 결정적 구문 분석을 할 수 없습니다. A -> aA  가 맞습니다. 강의 동영상을 참고하세요.
3.  따라서 각 생성규칙의 LOOKAHEAD는 다음과 같습니다.
   LOOKAHEAD(S->aSb) = {a}
   LOOKAHEAD(S->bA) = {b}
   LOOKAHEAD(A -> aA) = {a}
   LOOKAHEAD(A -> b) = {b}

질문에 대한 답변은 다음과 같습니다.
1. FOLLOW 계산시, 재귀가 발생하면 더 이상 원소의 변화가 없을 때 까지 연산을 수행하시면 됩니다.
2. 오타가 없는 문법을 기준으로 LL(1)을 만족합니다.
