### ISSUE TITLE
viable prefix, valid 질문

### ISSUE THREAD

**Issue by yoons02** [PLASS-Lab/CDT#4]
안녕하세요. 질문이 있어 issue 남깁니다.
viable prefix와 valid 개념이 잘 이해되지 않습니다.

먼저 viable prefix는 handle을 모두 보지 않은 상태라면 모두 viable prefix인가요?
예를 들어 S' -*> ab1b2b3 이고 b1b2b3가 handle이라면 ab1, ab2 두 개 다 viable prefix라고 봐도 되나요?

valid는 강의에서 ab1b2가 있을 때 b2가 epsilon이냐 아니냐를 가지고 shift할지, reduce할지 valid 정보를 보고 결정한다고 이해했습니다.
제가 이해한 것이 맞는지 확인 부탁드립니다

감사합니다

**Comment by PLASS-Lab** [comment]
1. Viable prefix는 문법의 우측 유도과정 중 임의의 생생규칙을 적용하고 있는 중간단계라고 보시면 됩니다.
    질문에서  **b1b2b3가 handle**이라면, viable prefix는 ab1, ab1b2, , ab1b2b3가 되겠습니다.

2.  viable prefix ab1 일 경우에는 아직 b2b3가 없으니 shift, 
     viable prefix ab1b2 일 경우에는 아직 b3가 없으니 shift, 
     viable prefix ab1b2b3 일 경우에 reducce 아이템이기 때문에(b3 뒤가 epsilon ) reduce 입니다.

     문법과 문장이 주어졌을 때, 임의의 우측 유도과정에서 viable prefix 있으면, 이 viable prefix 내의 우측 부분을 구성할 수 있는 LR()) 아이템을 valid하다고 합니다.

     S *=> aAw => ab1b2w, viable prefix ab1에 관해 LR(0) 아이템 [A->b1.b2]가 존재하면 해당 아이템을 valid 하다고 함.

      [A->b1.b2] 가 valid하면, 구문분석 과정 중 스택에 ab1이 들어가 있는 상황에서 shift, reduce를 결정할 수 있음. (b2가 epsilon이 아니라면 shift, epsilon이어서 [A->b1.] 와 마찬가지라면 reduce )
